image: golang:1.6

before_script:
- "go get -u github.com/sorcix/irc"
- "mkdir -p /go/src/maunium.net/go"
- "ln -s /builds/Tulir293/libmauirc /go/src/maunium.net/go/libmauirc"

build:
    script:
    - "env GOOS=linux GOARCH=amd64 go build -o lmitest_amd64 maunium.net/go/libmauirc/lmitest"
    - "env GOOS=linux GOARCH=arm go build -o lmitest_arm maunium.net/go/libmauirc/lmitest"
    - "env GOOS=windows GOARCH=amd64 go build -o lmitest.exe maunium.net/go/libmauirc/lmitest"
    stage: build
    tags:
    - golang
    artifacts:
        paths:
        - lmitest_amd64
        - lmitest_arm
        - lmitest.exe
        - LICENSE
